import type { MediaTranscriptionCacheItem, ProblemReport } from "./types";

export const DEMO = import.meta.env.VITE_DEMO === "true";

const now = Date.now();
const iso = (minsAgo: number) => new Date(now - minsAgo * 60000).toISOString();

export const demoReports: ProblemReport[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    user_id: "aaaa1111-1111-1111-1111-111111111111",
    issue_type: "wrong_audio",
    location: "dictionary detail",
    status: "open",
    language: "ja",
    message: "The audio reads 「いく」 but the word is 「ゆく」.",
    target: {
      kind: "tts_audio",
      surface: "dictionary detail",
      tts_cache_key: "ja:ゆく:v2",
      dictionary_entry_id: 152340,
    },
    client_context: {
      platform: "ios",
      app_version: "1.4.0",
      os_version: "iOS 18.5",
    },
    duplicate_count: 3,
    resolution_note: null,
    resolved_at: null,
    last_reported_at: iso(12),
    created_at: iso(45),
    updated_at: iso(12),
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    user_id: "aaaa2222-2222-2222-2222-222222222222",
    issue_type: "wrong_text",
    location: "capture result word sheet",
    status: "triaged",
    language: "ja",
    message: "Highlight grabbed the whole bubble, not just this word.",
    target: {
      kind: "capture_item",
      surface: "capture result word sheet",
      capture_id: "ca91-…",
      text_quote: "問題ない",
      boxes: [{ x: 120, y: 80, w: 64, h: 28 }],
    },
    client_context: { platform: "android", app_version: "1.3.2" },
    duplicate_count: 1,
    resolution_note: "Reproduced — OCR span merge bug, tracked in BACK-214.",
    resolved_at: null,
    last_reported_at: iso(200),
    created_at: iso(200),
    updated_at: iso(60),
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    user_id: "aaaa3333-3333-3333-3333-333333333333",
    issue_type: "wrong_definition",
    location: "dictionary detail",
    status: "resolved",
    language: "ja",
    message: "Definition says 'cat' but entry is 犬 (dog).",
    target: {
      kind: "dictionary_entry",
      surface: "dictionary detail",
      dictionary_source: "jmdict",
      dictionary_entry_id: 1234567,
    },
    client_context: { platform: "ios", app_version: "1.4.0" },
    duplicate_count: 1,
    resolution_note: "Fixed gloss in dictionary build 2026-06-05.",
    resolved_at: iso(1440),
    last_reported_at: iso(3000),
    created_at: iso(3000),
    updated_at: iso(1440),
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    user_id: "aaaa4444-4444-4444-4444-444444444444",
    issue_type: "other",
    location: "flashcard study",
    status: "dismissed",
    language: "ja",
    message: "App felt slow on this screen.",
    target: {
      kind: "screen",
      surface: "flashcard study",
      route: "/study/flashcards",
    },
    client_context: {
      platform: "android",
      app_version: "1.2.0",
      device_model: "Pixel 6",
    },
    duplicate_count: 1,
    resolution_note: "Not actionable — perf addressed in 1.4.",
    resolved_at: null,
    last_reported_at: iso(8000),
    created_at: iso(8000),
    updated_at: iso(7000),
  },
];

export const demoMediaTranscriptionItems: MediaTranscriptionCacheItem[] = [
  {
    source_type: "youtube",
    external_id: "y035IcEPiIA",
    media_id: "youtube:y035IcEPiIA",
    video_id: "y035IcEPiIA",
    source_url: "https://www.youtube.com/watch?v=y035IcEPiIA",
    gcs_object_key: "youtube/y035IcEPiIA/audio.m4a",
    title: "Kimino Koibitoni Nattara",
    channel: "back number",
    language: "ja",
    duration_seconds: 184.2,
    audio_updated_at: iso(90),
    status: "missing",
    provider: "",
    provider_model: "",
    payload_object_key: "",
    transcript_text: "",
    reviewed_at: null,
    error_detail: null,
    transcription_updated_at: null,
  },
  {
    source_type: "spotify_podcast",
    external_id: "demoSucceeded1",
    media_id: "spotify_podcast:demoSucceeded1",
    video_id: "",
    source_url: "https://open.spotify.com/episode/demoSucceeded1",
    gcs_object_key: "podcasts/demoSucceeded1/audio.m4a",
    title: "Japanese Listening Practice Podcast",
    channel: "Gravity Samples Show",
    language: "ja",
    duration_seconds: 642,
    audio_updated_at: iso(480),
    status: "succeeded",
    provider: "whisper",
    provider_model: "openai/whisper-large-v3",
    payload_object_key: "media-transcripts/demoSucceeded1/payload.json.gz",
    transcript_text: "これはデモ用の文字起こしです。管理画面から状態を確認できます。",
    reviewed_at: null,
    error_detail: null,
    transcription_updated_at: iso(300),
  },
  {
    source_type: "audio_url",
    external_id: "demoFailed1",
    media_id: "audio_url:demoFailed1",
    video_id: "",
    source_url: "https://example.com/audio/demoFailed1.m4a",
    gcs_object_key: "audio-url/demoFailed1/audio.m4a",
    title: "Unavailable Audio",
    channel: "Gravity Samples",
    language: "ja",
    duration_seconds: 245,
    audio_updated_at: iso(1200),
    status: "failed",
    provider: "openai",
    provider_model: "whisper-1",
    payload_object_key: "",
    transcript_text: "",
    reviewed_at: null,
    error_detail: "Provider transcription request failed.",
    transcription_updated_at: iso(240),
  },
];
